"""Textes d'interface, séparés du contenu technique des documents."""

LANGUAGES = {"en": "English", "fr": "Français", "darija": "Darija"}
TEXT = {
    "en": {
        "new": "New conversation", "documentation": "DOCUMENTATION", "tools": "TOOLS", "conversations": "CONVERSATIONS", "interface": "Interface language", "answer_language": "Answer language", "version": "Version", "ask": "Ask Documentation", "api": "API Search", "code_mode": "Explain Code", "error_mode": "Explain Error", "pdf": "My Documents", "search_mode": "Search documentation", "heading": "What do you want to understand?", "intro": "Ask about Python APIs, concepts, errors or code.", "question": "Ask Python documentation...", "send": "Ask", "try": "Try a question", "you": "YOU", "explanation": "Explanation", "code": "Code", "sources": "Sources", "passage": "View retrieved passage", "open": "Open documentation", "simplify": "Simplify", "example": "Give example", "deeper": "Explain deeper", "related": "Related questions", "searching": "Searching Python documentation...", "preparing": "Preparing answer...", "empty": "Enter a question first.", "missing_key": "GROQ_API_KEY is missing. Add it to Streamlit Secrets.", "no_results": "I couldn't find enough information in this documentation. Try an API name or rephrase your question.", "search_error": "Documentation search failed. Please retry.", "groq_error": "Groq is temporarily unavailable. Please retry.", "index_error": "The documentation index could not be loaded.", "api_name": "API name", "api_missing": "No exact match in this curated Python 3.13 index.", "related_apis": "Related APIs", "input_code": "Paste Python code", "input_error": "Paste an exception or traceback", "search": "Search", "result": "Result", "no_chat": "No conversation yet", "ready": "Index ready", "pdf_intro": "Upload a PDF to ask questions about your own document.", "pdf_file": "PDF file", "pdf_ready": "Document ready", "pdf_question": "Ask about this PDF", "pdf_empty": "This PDF is empty or exceeds the 10 MB limit.", "pdf_no_text": "No extractable text. Scanned PDFs need OCR.", "pdf_failed": "This PDF could not be processed.", "pdf_no_results": "No sufficiently relevant passage was found in this PDF.",
    },
    "fr": {
        "new": "Nouvelle conversation", "documentation": "DOCUMENTATION", "tools": "OUTILS", "conversations": "CONVERSATIONS", "interface": "Langue de l'interface", "answer_language": "Langue des réponses", "version": "Version", "ask": "Interroger la documentation", "api": "Recherche API", "code_mode": "Expliquer le code", "error_mode": "Expliquer une erreur", "pdf": "Mes documents", "search_mode": "Chercher dans la documentation", "heading": "Que voulez-vous comprendre ?", "intro": "Explorez les API, concepts, erreurs ou extraits de code Python.", "question": "Posez une question sur Python...", "send": "Envoyer", "try": "Quelques idées", "you": "VOUS", "explanation": "Explication", "code": "Code", "sources": "Sources", "passage": "Voir le passage retrouvé", "open": "Ouvrir la documentation", "simplify": "Simplifier", "example": "Donner un exemple", "deeper": "Approfondir", "related": "Questions liées", "searching": "Recherche dans la documentation Python...", "preparing": "Préparation de la réponse...", "empty": "Saisissez une question.", "missing_key": "Clé GROQ_API_KEY absente. Ajoutez-la aux Secrets Streamlit.", "no_results": "Pas assez d'informations dans cette documentation. Essayez un nom d'API ou reformulez la question.", "search_error": "La recherche dans la documentation a échoué.", "groq_error": "Groq est temporairement indisponible. Réessayez.", "index_error": "Impossible de charger l'index de documentation.", "api_name": "Nom de l'API", "api_missing": "Cette API ne figure pas dans notre sélection de Python 3.13.", "related_apis": "API liées", "input_code": "Collez du code Python", "input_error": "Collez une exception ou un traceback", "search": "Rechercher", "result": "Résultat", "no_chat": "Aucune conversation", "ready": "Index prêt", "pdf_intro": "Importez un PDF pour poser des questions sur votre document.", "pdf_file": "Fichier PDF", "pdf_ready": "Document prêt", "pdf_question": "Question sur ce PDF", "pdf_empty": "Ce PDF est vide ou dépasse la limite de 10 Mo.", "pdf_no_text": "Aucun texte extractible. Un PDF scanné nécessite un OCR.", "pdf_failed": "Impossible de lire ce PDF.", "pdf_no_results": "Aucun passage assez pertinent dans ce PDF.",
    },
    "darija": {
        "new": "Conversation jdida", "documentation": "DOCUMENTATION", "tools": "OUTILS", "conversations": "CONVERSATIONS", "interface": "Logha dyal l'interface", "answer_language": "Logha dyal ljawab", "version": "Version", "ask": "Sowel documentation", "api": "Qelleb 3la API", "code_mode": "Chra7 code", "error_mode": "Chra7 error", "pdf": "Documents dyali", "search_mode": "Qelleb f documentation", "heading": "Ach bghiti tfhem?", "intro": "Sowel 3la Python APIs, concepts, errors, ola code.", "question": "Sowel 3la Python...", "send": "Sowel", "try": "Jarrab soual", "you": "NTA", "explanation": "Chra7", "code": "Code", "sources": "Sources", "passage": "Chouf l passage", "open": "7ell documentation", "simplify": "Besset", "example": "3tini exemple", "deeper": "Chra7 ktr", "related": "As2ila mratbtin", "searching": "Kanqelleb f documentation Python...", "preparing": "Kanwejjed ljawab...", "empty": "Kteb soual lwwel.", "missing_key": "GROQ_API_KEY makaynach. Zidha f Streamlit Secrets.", "no_results": "Mal9itch ma3loumat kafya f had documentation. Jarrab smiya dyal API ola bdel soual.", "search_error": "Recherche f documentation ma khdematch.", "groq_error": "Groq daba ma khddamch. 3awed jarrab.", "index_error": "Index dyal documentation ma t7emmelch.", "api_name": "Smiya dyal API", "api_missing": "Had API makaynach f sélection Python 3.13.", "related_apis": "APIs mratbtin", "input_code": "Lseq code Python", "input_error": "Lseq error ola traceback", "search": "Qelleb", "result": "Resultat", "no_chat": "Mazal ma kaynach conversation", "ready": "Index wajed", "pdf_intro": "Upload PDF bach tsowel 3la document dyalek.", "pdf_file": "Fichier PDF", "pdf_ready": "Document wajed", "pdf_question": "Sowel 3la had PDF", "pdf_empty": "PDF khawi ola fayeq 10 MB.", "pdf_no_text": "Ma l9inach texte. PDF scan kay7taj OCR.", "pdf_failed": "Ma qdernach nqraw had PDF.", "pdf_no_results": "Ma l9inach passage monasib f PDF.",
    },
}


def t(key, language):
    return TEXT[language].get(key, TEXT["en"].get(key, key))
